### ISSUE TITLE
Undocumented necessity: data-scrollspy attribute

### ISSUE THREAD

**Issue by Abrahamlet** [huukimit/simple-scrollspy#1]
While trying to get the Bootstrap scrollspy plugin to work with a list of anchors  with no ordered or unordered lists, I came across this little plugin. Gave it a try but to no avail. But I kept playing with it and discovered an undocumented necessity.

For the elements (tabs) that will be given the "active" class when scrolling takes place, they all need the "data-scrollspy="#[desired_value]"" attribute. It functions as an href attribute on an anchor; its value must correspond to the value of an element's id on the page. Without this attribute, this plugin won't work at all.

Somehow this necessary attribute isn't documented. I discovered it while studying the html of the example. Things worked perfectly once I added it to my page.

Hope this helps.

**Comment by huukimit** [comment]
@Abrahamlet Thank you so much for your feedback. I will update documentation for `data-scrollspy` soon.

Btw, Let feel free to create a PR to make it awesome if you can. One day, the little plugin can save someone :)

**Comment by huukimit** [comment]
Hi @Abrahamlet,
In the new version 2.0.0, we will remove unnecessary attributes:`data-scrollspy` and `data-active`. The `href` attribute is used by default. Please check it: https://github.com/huukimit/simple-scrollspy/releases/tag/2.0.0

**Comment by Abrahamlet** [comment]
@huukimit 

Thanks for the update.
